name = "shell6"
type = "javascript"

compatibility_date = "2024-07-09"

[build]
command = "npm install"

[build.upload]
format = "service-worker"

[env.production]
name = "shell6"
compatibility_date = "2024-07-09"
route = "*/*"

[env.production.build]
command = "npm install"

[[build.upload.files]]
bucket = "dist"
exclude = ["**/*.map"]

[vars]
GITHUB_REPO = "https://github.com/erlandi-main-api/shell6"
