name = "shell6"
type = "javascript"

compatibility_date = "2024-07-09"

[build]
command = "npm install && npm run build"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"
entry-point = "."

[vars]
GITHUB_REPO = "https://github.com/erlandi-main-api/shell6"
